CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(30) NOT NULL UNIQUE,
  display_name VARCHAR(80) NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS teams (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  captain TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#c9ff47',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tournaments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  start_at TIMESTAMPTZ,
  last_draw_signature TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tournament_teams (
  tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  PRIMARY KEY (tournament_id, team_id)
);
CREATE TABLE IF NOT EXISTS matches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  round_no INTEGER NOT NULL,
  position INTEGER NOT NULL,
  team_a_id INTEGER REFERENCES teams(id), team_b_id INTEGER REFERENCES teams(id),
  score_a INTEGER, score_b INTEGER,
  handicap_a DOUBLE PRECISION NOT NULL DEFAULT 0,
  handicap_b DOUBLE PRECISION NOT NULL DEFAULT 0,
  scheduled_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'scheduled',
  voting_locked BOOLEAN NOT NULL DEFAULT FALSE,
  winner_id INTEGER REFERENCES teams(id),
  next_match_id INTEGER REFERENCES matches(id),
  next_slot TEXT CHECK (next_slot IN ('a', 'b')),
  UNIQUE (tournament_id, round_no, position)
);
CREATE TABLE IF NOT EXISTS votes (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  team_id INTEGER NOT NULL REFERENCES teams(id),
  awarded SMALLINT CHECK (awarded IN (-1, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, match_id)
);
CREATE INDEX IF NOT EXISTS matches_tournament_round_idx ON matches (tournament_id, round_no, position);
CREATE INDEX IF NOT EXISTS votes_match_idx ON votes (match_id);
CREATE INDEX IF NOT EXISTS votes_user_idx ON votes (user_id);
