CREATE TABLE IF NOT EXISTS tournament_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_tournament_id INTEGER,
  tournament_name TEXT NOT NULL,
  archived_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS match_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  history_id INTEGER NOT NULL REFERENCES tournament_history(id) ON DELETE CASCADE,
  round_no INTEGER NOT NULL,
  position INTEGER NOT NULL,
  team_a_name TEXT,
  team_a_captain TEXT,
  team_b_name TEXT,
  team_b_captain TEXT,
  score_a INTEGER,
  score_b INTEGER,
  winner_name TEXT,
  status TEXT NOT NULL,
  UNIQUE (history_id, round_no, position)
);

CREATE INDEX IF NOT EXISTS match_history_archive_idx
  ON match_history (history_id, round_no, position);
