CREATE TABLE IF NOT EXISTS tournament_vote_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_tournament_id INTEGER NOT NULL,
  source_final_match_id INTEGER NOT NULL UNIQUE,
  tournament_name TEXT NOT NULL,
  max_round INTEGER NOT NULL CHECK (max_round > 0),
  completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vote_history_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote_history_id INTEGER NOT NULL REFERENCES tournament_vote_history(id) ON DELETE CASCADE,
  source_match_id INTEGER NOT NULL,
  round_no INTEGER NOT NULL,
  position INTEGER NOT NULL,
  scheduled_at TIMESTAMPTZ,
  team_a_source_id INTEGER NOT NULL,
  team_a_name TEXT NOT NULL,
  team_b_source_id INTEGER NOT NULL,
  team_b_name TEXT NOT NULL,
  score_a INTEGER,
  score_b INTEGER,
  handicap_a NUMERIC(10,2) NOT NULL DEFAULT 0,
  handicap_b NUMERIC(10,2) NOT NULL DEFAULT 0,
  winner_source_id INTEGER,
  winner_name TEXT,
  source_user_id INTEGER NOT NULL,
  username TEXT NOT NULL,
  display_name TEXT NOT NULL,
  voted_team_source_id INTEGER NOT NULL,
  voted_team_name TEXT NOT NULL,
  awarded SMALLINT CHECK (awarded IN (-1, 1)),
  voted_at TIMESTAMPTZ NOT NULL,
  removed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (vote_history_id, source_match_id, source_user_id)
);

CREATE INDEX IF NOT EXISTS tournament_vote_history_completed_idx
  ON tournament_vote_history (completed_at DESC);

CREATE INDEX IF NOT EXISTS vote_history_entries_history_idx
  ON vote_history_entries (vote_history_id, round_no, position, source_match_id);
